### ISSUE TITLE
Python code fails on "local variable 'baa' referenced before assignment"

### ISSUE THREAD

**Issue by wiz21b** [blissville71/STORM#7]
Running the code with the given examples, I get:
``` 
Thank you for using STORM. Your variable settings are: 
['Type of Model Run = ', 'Validation']
['Number of Simulations = 1']
['Number of Simulation Years = 10']
Number of Seasons = Two
Scenario of Total Precipitation (Season 1) = Control climate
Scenario of Precipitation Intensity (Season 1) = Control climate
Scenario of Total Precipitation (Season 2) = Control climate
Scenario of Precipitation Intensity (Season 2) = Control climate
Scenario of ET = Control climate
/home/stefan/Dropbox/uliege/tfe/STORM/model_input/bndry_buffer/bndry_buffer.shp
Traceback (most recent call last):
  File "/home/stefan/Dropbox/uliege/tfe/STORM/STORM.py", line 1452, in <module>
    SM, GM, Dur = storm(mode='Validation', numsims=1, numsimyrs=10, seasons=2,
  File "/home/stefan/Dropbox/uliege/tfe/STORM/STORM.py", line 934, in storm
    if baa == 'a':
UnboundLocalError: local variable 'baa' referenced before assignment

```

**Comment by wiz21b** [comment]
Reading other issues, I think this one is quite like issue #3

**Comment by wiz21b** [comment]
Funny, on the second run it doesn't crash anymore...
